name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Test building
    runs-on: ubuntu-20.04

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install libboost-all-dev libwebsocketpp-dev ninja-build nlohmann-json3-dev
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build library & tests
      run: ./compile_all.sh
    - name: Run tests
      run: ./run_tests.sh
