name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Test building
    runs-on: ubuntu-latest

    steps:
    - name: Add Kody PPA for a dependency
      run: sudo add-apt-repository ppa:team-xbmc/xbmc-nightly
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install libboost-all-dev libwebsocketpp-dev ninja-build nlohmann-json3-dev
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build library
      run: ./build.sh
    - name: Run tests
      run: ./run_tests.sh
