name: Release docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install doxygen graphviz
    - uses: actions/checkout@v2
    - name: Generate documentation
      run: doxygen
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc
        publish_branch: gh-pages
        force_orphan: true
